## Time-stamp: <2011-09-20 15:38:55 vk>
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/

What were you doing on February 14th of 2007? On which tasks were you
working on that very day you met your girl friend? When was the last
appointments with your dentist? Who called you on telephone during
that meeting with your customer last month?

Most people can not answer such questions. With Memacs you can!

Memacs extracts metadata (subjects, timestamps, contact information,
...) from many different existing data sources (file names, emails,
tweets, bookmarks, ...) on your computer and generates files which are
readable by [[http://en.wikipedia.org/wiki/Emacs][GNU Emacs]] with [[http://orgmode.org][Org-mode]].

Memacs - as the central component of the system - is a hub for all the
connectors that add data from individual data sources. Those connectors
are called «Memacs modules» or short «module».

For best practices, frequently asked questions and their answers
please refer to the file FAQs_and_Best_Practices.org


* Example Story

Imagine you are already using a Memacs.

When remembering that day, when you joined an interesting talk about
"[[http://en.wikipedia.org/wiki/Getting_Things_Done][Getting Things Done]]" (GTD), you start up your GNU Emacs with your main
Org-mode file. There you go to the Agenda-view and select this
specific day a couple of months ago.

There it is, from 2pm to 3pm you scheduled this talk in your
calendar. And then you realize that within this time frame, there
appear some [[http://en.wikipedia.org/wiki/Jpeg][JPEG files]] containing an [[http://www.cl.cam.ac.uk/~mgk25/iso-time.html][ISO 8601]] time stamp (with periods
instead of colons - just because the [[http://msdn.microsoft.com/en-us/library/aa365247(v%3Dvs.85).aspx#naming_conventions][ancient limitations of Microsoft
based file systems]]; like "2011-02-14T14.35.42 ideas.jpg") are indexed
by one module. (filenametimestamp-module)

This image contains a slide you found interesting and which you
photographed using your sleek smartphone. Who would remember having
taken a picture during a talk?

Ten minutes after the talk you wrote a short message on [[http://Titter.com][Twitter]] where
you mentioned useful URLs for your followers. This time those URLs are
handy for yourself too! (Twitter-module)

On the evening of that day you see an entry of an incoming email from
the author of the talk. Now you remember having had a cool
conversation at the end of the talk where he promised you some
additional information about that nice little GTD tool on his
computer. Great that you got that link to that email too. Without
Memacs you would probably never got to that email
again. (Maildir-module)

And then there were some bookmarks you saved this day, almost all
related to ideas you got from the GTD talk. (delicious-module)

This small story shows only a few use cases where different modules
combine given data sources and their information to provide an overall
view related to an event. Since Org-mode has got links, no actual data
has to be duplicated (except the small meta data extracted by
Memacs). Emails, files, bookmarks, and so forth are linked rather than
copied.


* Memacs Modules

This section contains a list of current and future modules which
extract data from all kinds of data sources.

Existing modules:

- file name timestamps
  - see filenametimestamps/works-for-me-hack/memacs-filenametimestamps.org
- emails/mbox-format
  - see emails/mbox_and_newsgroup_postings/works-for-me-hack/memacs-mbox.org

Those modules will be developed in the next weeks or months:

- bookmarks/delicious
  - see bookmarks/delicious/memacs-delicious.org

- emails/Maildir
  - see emails/maildir/memacs-maildir.org


** twitter/grabeeter

[[http://grabeeter.tugraz.at/][Grabeeter]] is a free online service of [[http://www.TU-Graz.at][Graz University of Technology]]
where you can search and archive your tweets from [[http://Twitter.com][Twitter]].

Maybe there will be a future module which accesses a [[http://andrewprice.me.uk/projects/twyt/][Twitter API]]
but for now we will stick to the faster and more reliable Tweet
archiving service of Grabeeter.

Tweets like this one from user "n0v0id" will appear like this:

: ** <2011-05-02 Mon 16:12> [[http://twitter.com/n0v0id/status/64966447897653248][Hello World!]] :n0v0id:Twitter:Memacs:


** TODO tagstore

[[http://tagstore.org][tagstore]] is a research software that stores local files using tags and
derives associative navigational folder structures from the tags of
the files.

This module collects events like adding a new file to a store and
generates entries like this: (the file was tagged with "CustomerA" and
"ProjectB")

: ** [[file:~/tagstore/Invoice_0815.pdf][Invoice_0815.pdf]]  :ProjectB:CustomerA:tagstore:Memacs:
:   <2011-07-23 Sat 15:50>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 15:50>
:   :END:


** TODO GoogleCalendar

We might be able to provide a module that gets events from a [[http://www.google.com/calendar][Google
calendar]] using [[http://code.google.com/apis/calendar/data/2.0/developers_guide_python.html][an API]].

Those calendar events might be looking like this:

: ** <2011-07-23 Sat 14:00-15:30> [[http://example.com/link/to/event][Meeting with Customer]]      :GCal:Memacs:


** TODO git

[[http://en.wikipedia.org/wiki/Revision_control][Version control systems]] are quite common to manage all kind of data
with. [[http://en.wikipedia.org/wiki/Git_(software)][git]] is a modern distributed system that has an enormous feature
set.

Whenever user "Bob" commits a change set to an example project called
"myproject", git-module can provide an entry like this:

: ** myproject (Bob): solved the address field bug         :git:Menacs:
:   <2011-07-23 Sat 16:00>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:00>
:   :COMMIT: 528bb77ba94592bd86cd4bbe38bcb3ee9dcc276e
:   :END:


** TODO Subversion (versioning_system/svn)

Version control systems]] are quite common to manage all kind of data
with. [[http://en.wikipedia.org/wiki/Apache_Subversion][Subversion (SVN)]] is a modern system that is widely used for
revision control.

Whenever user "Bob" commits a change set (resulting in revision 42) to
an example project called "myproject", svn-module can provide an entry
like this:

: ** myproject (Bob) r42: solved the address field bug       :svn:Menacs:
:   <2011-07-23 Sat 16:00>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:00>
:   :REVISION: 42
:   :END:


** TODO SMS

We are thinking about a module that extracts [[http://en.wikipedia.org/wiki/SMS][Short Message Service
(SMS)]] messages from a backup of your [[http://en.wikipedia.org/wiki/Android_(operating_system)][Android]] smartphone. We have to
test various methods before being able to tell more.

Probably such an SMS might look like:

: ** "Hello brother, how are you?"               :SMS:Memacs:
:   <2011-07-23 Sat 16:09>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:09>
:   :FROM-NUMBER: 00436641234567
:   :END:


** TODO mobile-calls

Any [[http://en.wikipedia.org/wiki/Android_(operating_system)][Android]] smartphone logs your phone calls. Various software tools
let you backup those call logs to your computer. This module takes
those call logs and puts it into your Agenda - right where it belongs
to.

Probably a mobile phone call might look like:

: ** call from: 00436641234567               :phone:Memacs:
:   <2011-07-23 Sat 16:19>-<2011-07-23 Sat 16:21>
:   :PROPERTIES:
:   :CREATED: <2011-09-23 Fri 14:09>
:   :FROM-NUMBER: 00436641234567
:   :END:


** SOMETIME JPilot-todo

[[http://www.jpilot.org/][J-Pilot]] is a software that were used by many [[http://en.wikipedia.org/wiki/Palm_OS][Palm OS]] users on
GNU/Linux. It contains your Palm OS agenda, todos, contact
informations, and memos.

Since many users still appreciate the [[http://www.pimlicosoftware.com/datebk6.htm][mature software]] to organize
their life, this module generates Org-mode entries from J-Pilot export
data.

Such an todo entry might look like this:

: ** TODO buy new shoes                              :errands:jpilot:Memacs:
:   DEADLINE: <2011-07-29 Fri>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:16>
:   :END:


** SOMETIME JPilot-events

[[http://www.jpilot.org/][J-Pilot]] is a software that were used by many [[http://en.wikipedia.org/wiki/Palm_OS][Palm OS]] users on
GNU/Linux. It contains your Palm OS agenda, todos, contact
informations, and memos.

Since many users still appreciate the [[http://www.pimlicosoftware.com/datebk6.htm][mature software]] to organize
their life, this module generates Org-mode entries from J-Pilot export
data.

Such an calendar entry might look like this:

: ** Meeting with big boss                    :jpilot:Memacs:
:   <2011-07-29 Fri 11:00-14:00>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:16>
:   :END:


** SOMETIME blog_systems/serendipity

[[http://www.s9y.org/][Serendipity]] is a Weblog software tool. This module requires an XML
backup of a Serendipity export and generates an Org-mode entry for
each blog entry submission:

: ** Why I hate Mondays and what to do about it         :serendipity:Memacs:
:   <2011-07-23 Sat 12:15>
:   :PROPERTIES:
:   :CREATED: <2011-07-23 Sat 16:20>
:   :END:


* Background

In 1945, [[http://en.wikipedia.org/wiki/Vannevar_Bush][Vannevar Bush]] wrote a famous article "[[http://en.wikipedia.org/wiki/As_We_May_Think][As We May Think]]" where
he develops the idea of having a "memory extender" called Memex. The
memex can store all letters, books, and other information which are
related to a person.

Besides having foreseen several technologies like hypertext, he
defined a device that holds all metadata and data and provides
associative trails to access information.

In the last decade of the previous century Microsoft Research had a
research program that resulted in [[http://en.wikipedia.org/wiki/MyLifeBits][MyLifeBits]]. This software tried to
store each information of the user like office documents, screenshots,
name of active windows on the desktop computer, and even automatically
took photographs ([[http://en.wikipedia.org/wiki/Sensecam][SenseCam]]). This word did not result in any (open)
software product. Bell and Gemmell wrote a book called "[[http://www.amazon.de/gp/product/0525951342/ref%3Das_li_ss_tl?ie%3DUTF8&tag%3Dkarlssuder-21&linkCode%3Das2&camp%3D1638&creative%3D19454&creativeASIN%3D0525951342][Total Recall]]".

The Memacs project tries to implement the ideas of Vannevar Bush's
vision with open source and open standards. It's name "Memacs" is the
obvious combination of "GNU Emacs" and "Memex".

Memacs uses GNU Emacs Org-mode to visualize and access information
extracted by Memacs modules: using tags, time stamps, full text
search, and so forth GNU Emacs is able to derive different
views. The most important view probably is the [[http://orgmode.org/org.html#Agenda-Views][Agenda-view]] where you
can see anything that happened during a specific day/week/month
according to the time frame selected. But you can derive other views
too. For example you can choose to generate a condensed search result
using a [[http://en.wikipedia.org/wiki/Boolean_algebra_(logic)][boolean combination]] of tags.

Deeply related to Memacs, the project leader developed a research
software [[http://tagstore.org][tagstore]]. This system allows users to store (local) files
using tags an not a hierarchy of folders. As a natural extension,
tagstore targets associative access for (local) files. You might want
to check out tagstore too. Memacs and tagstore are a very useful
combination.


* Contribute! We are looking for your ideas:

If you want to contribute to this cool project, please fork and
contribute or write an additional module!

We are sure that there are a *lot* of cool ideas for other modules out
there!

Memacs is designed with respect to minimal effort for new modules.

We are using [[http://www.python.org/dev/peps/pep-0008/][Python PEP8]] and [[http://en.wikipedia.org/wiki/Test-driven_development][Test Driven Development (TDD)]].
