## Time-stamp: <2011-10-09 13:52:42 vk>
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/

* memacs-easybank

** Current status

This module currently is a quick hack with status «works for me». Feel
free to improve this module. It is highly dependent of bank statements
from (Austrian) [[http://easybank.at][easybank]] bank statements. Since there does not seem to
be a standard for the single large description field, many things are
related to personal payment habits.

** Data Source

Easybank offers a download for bank data on the online banking system
web page. For now (2011-11), do not search for CSV at the bank
statement feature «Kontoauszüge» which offers only PDF files. You can
download your account information at the transaction volume feature
«Umsätze».

Some example lines might look like:
: 20010361118;Auszahlung Maestro                           MC/000002322|BANKOMAT 32781 KARTE1 07.10.UM 17.50;07.10.2011;07.10.2011;-20,00;EUR
: 20010361118;present                                      FE/000002422|13000 51642031132 Michael Test;07.10.2011;07.10.2011;-10,00;EUR
: 20010361118;Kletterpark                                  FE/000002420|34000 00059241492 Joe Average;05.10.2011;05.10.2011;-25,00;EUR

** Example Invocation

The simplest example is when you are processing only one CSV file:

: ~/bin/memacs-easybank.py -f ~/bank/last_data.csv >>~/org/bank.org

If you have multiple mbox files you want to process, you can stick to
following example. First, the old Memacs file is removed. Then several
files are parsed and the [[http://en.wikipedia.org/wiki/Stdout#Standard_output_.28stdout.29][stdout]] is written to the new Memacs file:

: rm ~/org/bank.org; for file in ~/bank/*data.csv ; do ~/bin/memacs-easybank.py -f "${file}" >>~/org/bank.org ; done

** Example Orgmode entries

: ## -*- coding: utf-8 -*-
: * bank transactions                          :Memacs:bank:
: ** <2011-05-16> +400,00€, [[contact:Company Foo][Company Foo]], [[bank:16.05.2011;16.05.2011;+400,00][Bill 4711]]
: ** <2007-06-04> -43,76€, [[contact:John Doe][John Doe]], [[bank:04.06.2007;04.06.2007;-43,76][Internet march 07]]
: ** <2007-08-03 16:45> -15,00€, [[contact:ATM 2345][ATM 2345]], [[bank:03.08.2007;03.08.2007;-43,76][drawing]]


