## Time-stamp: <2012-05-30 18:23:28 armin>
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/

* Best Practices

** Invocation

Most of the time you probably want to invoke Memacs modules
automatically and periodically. Here are some tips for achieving this.

For each Memacs module there is documentation <memacs_module.org> located in the same
folder as the file. Additionally you can get help for each module by
executing it with the "-h" argument e.g.:
: ./bin/memacs_module.py -h

*** Important: Pythonpath environment variable
Memacs folder has to be on the PYTHONPATH. Just google for it how to set it.

If using crontab you have to set it there too. You can put following line on top:
: PYTHONPATH=/path/to/Memacs

*** GNU/Linux (like Ubuntu, SuSE, RedHat, Debian, ...)

You are lucky because [[http://en.wikipedia.org/wiki/Cron][cron]] is providing a fairly easy to use interface
for this!

Wikipedia is offering [[http://en.wikipedia.org/wiki/Cron#Predefined_scheduling_definitions][a cool example section]] on how to generate
cronjob entries. Most of the time you only have to call «crontab -e»
and you can start entering a line.

*** Mac OS X

Older versions of Mac OS X used to support cron. But since OS X 10.4 «Tiger» you have to use [[http://en.wikipedia.org/wiki/Launchd][launchd]] instead.

*** Microsoft Windows

Please refer to [[http://support.microsoft.com/kb/308569][Windows Task Scheduler]].

** Error Handling
Because we let our memacs-modules automatically run, it would be difficult
to get informed in case of an error. So memacs-modules have a nice error handling:

When you specify an outputfile like this:

: memacs-module.py -o /path/to/output.org_archive

Then errors are automatically added to
: /path/to/error.org

- Create the file containing following information:
  : ## -*- coding: utf-8 mode: org -*-
  : ## this file is for error-messages of Memacs
  : ## to add this file to your org-agenda open error.org with emacs and: M-x org-agenda-file-to-front
  : ##
  : ## Main idea of this file:
  : ## if a memacs-module has an error following entry will be generated:#
  : ## ** <TIMESTAMP-ERROR-occured +1d> memacs-foo had a problem: <error-msg> #
  : ## the "+1d" means that this entry will appear in org agenda view until the entry is deleted from this file
  : ##
  : * Memacs error 					      :Memacs:ERROR:
  : # start deleting from here:

- Add the file to Org-Agenda:
  - open the file in emacs and M-x org-agenda-file-to-front

If an error occurs it will be added to the error.org with an repeating timestamp every day.
You have to delete the error manually.

** Autotagging
Autotagging allows tags to be set for each entry automatically.

For now autotagging is only available for the <headline> of the entry.

: *** <1900-00-00> <headline> :tags:
:     <additional data>
:     :PROPERTIES:
:     :END:

*Example Autotag file:*
: [autotag]
: haha=foo, fooo bar, foobar
: lala=bar, baaar

*Autotag file style:*
: [autotag]
: <TAG>=names to match for that tag seperated by a comma
: <TAG>=....
: ....

*Example file without Autotag:*
: ** <1970-01-01 Thu 00:00> foo
: ** <1970-01-01 Thu 00:00> bar	:tag1:tag2

*Example file with Autotag:*
: .../bin/memacs_example.py --autotag /tmp/autotags

: ** <1970-01-01 Thu 00:00> foo	:haha:
: ** <1970-01-01 Thu 00:00> bar	:tag1:tag2:lala:

** Performance and Scalability

*** File names of generated Memacs files: archive

Memacs is usually generating [[http://orgmode.org/org.html#Archiving][Org-mode archive files]]:

- «emails.org» ... only a stub
- «emails.org_archive» ... containing Orgmode heading lines with
  Memacs data

This has following advantage: in normal mode, Memacs entries do
not interfere with the Org-mode data you are processing daily. It is
as fast as usual.

Only when you choose to view also the archive files ([[http://orgmode.org/org.html#Agenda-commands]["v A" in
Agenda-view]]) you get the data Memacs displayed in your Orgmode Agenda.

This should not lead to any slow down in your daily work while having
the tremendous opportunity to get the verbose information on demand.

**** How to use archive files

1. generate a stub file like «~/org-mode/files.org»
2. you might want to enter some information there but you can as well
   leave the file empty
3. let Memacs generate your Org-mode archive file like «~/org-mode/files.org_archive»
4. open «~/org-mode/files.org» in your GNU Emacs and invoke «M-x org-agenda-file-to-front»
5. You successfully added this Memacs module to your Org-mode Agenda
6. Whenever you want to see the entries of «files.org_archive» (or any
   other archive file) in your Agenda, invoke «v A» when you are in
   your normal Agenda view.

See:  [[http://orgmode.org/org.html#Agenda-commands]["v A" in Agenda-view]]

*** Performance of Agenda

I am using Org-mode with following archive files:

:   lines kByte file
:   24493  4476 files.org_archive
:    5919  1222 mbox.org_archive
:    5117   927 news.org_archive
: ---------------------------------
:   35529  6625 total

Starting the «normal» Agenda (without archive files activated) is not
affected by the *.org_archive files at all.

When I am in agenda view and I switch to the agenda entries as well
(using «v A»), I face a delay of less than four seconds.

After that it depends on how many entries you have got for that
specific view (day, week, ...). I get only a slightly worse feedback
then. But it is perfectly usable to me.

*** SSD versus HDD

By using [[http://en.wikipedia.org/wiki/Ssd][SSD]]s instead of hard disks, you get a huge performance
boost. For example lets see following command:

: find /home -name '[12][0-9][0-9][0-9]-[01][0-9]-[0123][0-9]*' -type f 2>/dev/null | \
: egrep -v '(/s/|temporary|/\.|/restricted/)' > /tmp/files-tmp && \
: ~/bin/memacs-filenametimestamps.py -f /tmp/files-tmp \
:        -w -o ~/org-mode/memacs/files.org_archive

It crawls over 132,000 files of my home folder, filters using an
[[http://en.wikipedia.org/wiki/Regex][regular expression]], removes paths containing temporary or restricted
folders, and generates Orgmode Memacs entries for over 24,000 files
resulting in four and a half megabytes of file size.

This command does not take longer than *two and a half seconds* on an
SSD which is quite remarkable. Using a normal hard disk, a comparable
call takes *one minute and fifteen seconds*.


** File organization

The more Memacs modules you are using, the more files (*.org and
*.org_archive) you get in your (single?) Orgmode-folder.

You might want to create a separate Memacs folder containing all
generated Memacs Orgmode files:


: /home/user/orgmode/work.org
: /home/user/orgmode/work.org_archive
: /home/user/orgmode/private.org
: /home/user/orgmode/private.org_archive
: /home/user/orgmode/memacs/module1.org
: /home/user/orgmode/memacs/module1.org_archive
: /home/user/orgmode/memacs/module2.org
: /home/user/orgmode/memacs/module2.org_archive
: /home/user/orgmode/memacs/error.org          <- See Section Error Handling
** Power Consumption while being on battery

When you are using Memacs on a notebook, you might not want to execute
certain cron jobs while being on battery power only.

Ubuntu GNU/Linux is using the [[http://en.wikipedia.org/wiki/Procfs][proc file system]] where you can access
many hardware-related information such as battery state:

: vk@gary ~ % cat /proc/acpi/battery/BAT0/state
: present:                 yes
: capacity state:          ok
: charging state:          charged
: present rate:            0 mW
: remaining capacity:      35290 mWh
: present voltage:         12526 mV
: vk@gary ~ %
:
: ## now I disconnect the battery from external power supply
:
: vk@gary ~ % cat /proc/acpi/battery/BAT0/state
: present:                 yes
: capacity state:          ok
: charging state:          discharging
: present rate:            18452 mW
: remaining capacity:      35270 mWh
: present voltage:         12426 mV
: vk@gary ~ %

With a simple shell script named «no-power-supply.sh», you can execute cron job commands only
when having external power supply:

: #!/bin/sh
: grep discharging /proc/acpi/battery/BAT0/state >/dev/null

or if you have more than one battery:

: #!/bin/sh
: grep discharging /proc/acpi/battery/BAT0/state /proc/acpi/battery/BAT1/state >/dev/null

Then some example cron jobs look like:

: 5-59/10 1,8-23 * * * /usr/local/bin/no-power-supply.sh || /home/vk/bin/do_some_things.sh
: 10 * * * * /usr/local/bin/no-power-supply.sh || { find ....  | egrep '...' > tmpfile && do_that.sh }

Whenever your notebook is in state «discharge» those cronjobs are not
being executed.


* Internals
** How to write a memacs module?
see
: Memacs/bin/memacs_example.py
: Memacs/memacs/example.py
: Memacs/tests/example_test.py
** Testing
Use [[http://readthedocs.org/docs/nose/en/latest/][nosetests]] for executing tests
install it with:
: % easy_install nosetests
or
: # aptitude install python-nose
** how works the *appendmode* of memacs? / How is the :ID: Property generated?
All properties (:PROPERTIES: drawer) are stored in a dict
: i.e.: :FOO: <bar>
: key = "FOO , value = <bar>

generation:
: id-hash = sha1(<all values> + <all keys>)

Before writing an entry to the org-file, the id is generated.

If Memacs module is in appendmode, it looks for those :ID: properties
and stores them in a list. On writing(append) it first checks against that list.

*** what to do if our :PROPERTIES: give not enough unique data?
    ... so that a hash cannot be unique too?

    you can set OrgProperties(data_for_hashing="more_data") for this problem


* FAQs
If you have one question, please contact «Karl dot Voit
at IST dot TUGraz dot at» and he is happy to answer it.

** Emacs always complains what to do with changed org files
Solution is to add this to your emacs config file (.emacs):
: (global-auto-revert-mode t)
