#  -*- mode: org -*-
# This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/

* memacs-mumail

Please report any problems you find opening a new issue
or writing an email to [[mailto:memacs-mumail@m.stennes.org][memacs-mumail@m.stennes.org]]

** Options

- ~-q~, ~--query~, mu search query
- ~-m~, ~--me~, space separated list of mail addresses that belongs to you
- ~-d~, ~--delegation~, adds NEXT or WAITING state to flagged messages

** Data Source

This memacs module will parse your emails after they are indexed by
[[http://www.djcbsoftware.nl/code/mu/][mu]].  Clickable links have just been tested with [[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] (an emacs-based
e-mail client based on mu) as frontend.

Look [[https://gist.github.com/areina/3879626][here]] for how to set up mu4e with offlineimap.

** Example Invocation
*** Basic Invocation

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir'" -m "you@domain.org"

The -m param with your email address will check if the mail ewas from
or to you.

An entry with an email from you will look like this:

: ** <2011-11-03 Do 13:31> F: [[mailto:sender@domain.org][Sender Name]]: [[mu4e:msgid:1554232683.7822665.1320323516478.JavaMail.fmail@mwmweb024][subject]]
:   :PROPERTIES:
:   :TO:         Your Name <you@domain.org>
:   :FROM:       [[mailto:sender@domain.org][Sender Name]]
:   :ID:         638a689e6e40abe4f3ae1da6834da42f44082577
:   :END:

An entry with an email to you will look like this

: ** <2012-07-05 Do 21:21> T: [[mailto:recipient@domain.org][Recipient Name]]: [[mu4e:msgid:3EDBEB35-D9CA-4A10-8582-A98A65B30097@arcor.de][Re: subject]]
:   :PROPERTIES:
:   :TO:         Recipient Name <recipient@domain.org>
:   :FROM:       [[mailto:you@domain.org][Your Name]]
:   :ID:         591a0dcf4bf83c8b508324c7c954d2e7b1a0b822
:   :END:

*** Advanced Invocation

You can use the -q param with every input for mu find that is
supported by mu. Check out [[http://www.djcbsoftware.nl/code/mu/cheatsheet.html][Mu Cheatsheet]] and [[http://manpages.ubuntu.com/manpages/lucid/man1/mu-find.1.html][ubuntu manuals mu]].

**** Unread emails

For people using the agenda a lot, it could be nice to see new
(unread) emails directly on the agenda. The following invocation will
list just all unread mails in your Maildir

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir' and flag:unread" -m "you@domain.org"

To see the emails on your agenda add the -o param and include the
selected .org-file (not .org_archive) to your org-agenda-files.

**** Flagged emails

Do you know this: You check your mails on the road, but you do not
have time to reply and when you are at home you forget it?

With this option flagged mails will appear on your agenda:

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir' and flag:flagged" -m "you@domain.org -d"

If you add the param -d, messages in your INBOX that are flagged will
be marked as NEXT and messages in your Sent folder will be marked as
WAITING.

Entry for a flagged email in your INBOX

: ** NEXT <2011-11-03 Do 13:31> F: [[mailto:sender@domain.org][Sender Name]]: [[mu4e:msgid:1554232683.7822665.1320323516478.JavaMail.fmail@mwmweb024][subject]]
:   SCHEDULED: <2011-11-03 Do>
:   :PROPERTIES:
:   :TO:         Your Name <you@domain.org>
:   :FROM:       [[mailto:sender@domain.org][Sender Name]]
:   :ID:         638a689e6e40abe4f3ae1da6834da42f44082577
:   :END:

Entry for a flagged email in your Sent folder

: ** WAITING <2012-07-05 Do 21:21> T: [[mailto:recipient@domain.org][Recipient Name]]: [[mu4e:msgid:3EDBEB35-D9CA-4A10-8582-A98A65B30097@arcor.de][Re: subject]]
:   SCHEDULED: <2012-07-05 Do>
:   :PROPERTIES:
:   :TO:         Recipient Name <recipient@domain.org>
:   :FROM:       [[mailto:you@domain.org][Your Name]]
:   :ID:         591a0dcf4bf83c8b508324c7c954d2e7b1a0b822
:   :END:

To see the emails on your agenda, add the -o param and include the
selected .org-file (not .org_archive) to your org-agenda-files.

To get both unread and flagged emails use the following invocation

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir' and flag:flagged or maildir:'/YourMaildir' and flag:unread " -m "you@domain.org"

**** Using a catch-all domain

When you are using a catch-all domain, you can use the following
invocation to check whether the email was sent from or to you.

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir'" -m "@domain.org"

For the case that you are using a catch-all domain (e.g. as subdomain)
and another address at the same time you can use:

: $ memacs_mumail.py -q "mu find maildir:'/YourMaildir'" -m "you@domain.org @sub.domain.org"
